config/routes.rb
FantasySandbox::Application.routes.draw do
  root to: 'leagues#index'
  resources :leagues, only: [:index]
  match 'buffalo', to: 'buffalo#index', via: 'get'
end

app/models/buffalo.rb
class Buffalo

  attr_accessor :data

  def initialize
    @data = JSON.parse(File.read(File.join(Rails.root, 'lib', 'assets', 'buffalo.json')))
  end
end

app/models/league.rb
class League

  attr_accessor :data

  def initialize
     @data = JSON.parse(File.read(File.join(Rails.root, 'lib', 'assets', 'standings.json')))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/buffalo_controller.rb
class BuffaloController < ApplicationController

  def index
    buffalo = Buffalo.new
    @data = buffalo.data
  end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController

  def index
    league = League.new
    @data = league.data
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/views/buffalo/index.html.erb
<div>
  <table class="table table-bordered table-condensed">
    <thead>
    <tr>
      <th>Player</th>
      <th>Position</th>
      <th>FantasyPoints</th>
      <th>Touchdowns</th>
      <th>ReceivingYards</th>
    </tr>
    </thead>
    <tbody>
    <% @data.each do |player| %>
        <tr>
          <td><%= player['Name'] %></td>
          <td><%= player['FantasyPosition'] %></td>
          <td><%= player['FantasyPoints'] %></td>
          <td><%= player['Touchdowns'] %></td>
          <td><%= player['ReceivingYards'] %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Fantasy Sandbox", root_path, id: "logo" %>
      <nav>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FantasySandbox</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<%= yield %>

</body>
</html>

app/views/leagues/index.html.erb
<div>
<table class="table table-bordered table-condensed">
  <thead>
  <tr>
    <th>Team</th>
    <th>Wins</th>
    <th>Losses</th>
  </tr>
  </thead>
  <tbody>
  <% @data.each_with_index do |team, index| %>
  <% if index == 0 %>
  <tr>
    <td><%= link_to(team['Name'], buffalo_path) %></td>
    <td><%= team['Wins'] %></td>
    <td><%= team['Losses'] %> </td>
  </tr>
  <% next %>
  <% else %>
  <% end %>
  <tr>
    <td><%= team['Name'] %></td>
    <td><%= team['Wins'] %></td>
    <td><%= team['Losses'] %> </td>
  </tr>
  <% end %>
  </tbody>
</table>
</div>